import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Menubar from '@/components/Menubar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className='flex flex-row justify-center w-[100%] my-4'>
        <Menubar />
      </div>
        {children}
      </body>
    </html>
  )
}
